/**
 * Characterization tests: the TypeScript RndcClient must produce byte-identical
 * XML/SOAP output to the PHP original. Fixtures are generated by
 * `php server/test/gen_rndc_fixtures.php` (RndcClient.php is the source of truth).
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import iconv from 'iconv-lite';
import { describe, it, expect } from 'vitest';
import { RndcClient } from '../src/rndc/RndcClient.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const fixtures = JSON.parse(readFileSync(path.join(__dirname, 'rndc_fixtures.json'), 'utf8')) as Record<
  string,
  { input: Record<string, unknown>; output: string }
>;

// Same credentials as gen_rndc_fixtures.php.
const rndc = new RndcClient('miUsuario', 'miClave&<>', 'pruebas', '', 30);

describe('RndcClient parity with PHP', () => {
  it('construirXmlInterno matches byte-for-byte', () => {
    const f = fixtures.construirXmlInterno!;
    const out = rndc.construirXmlInterno(
      f.input.tipo as string,
      f.input.procesoid as number,
      f.input.variables as Record<string, string | null>,
    );
    expect(out).toBe(f.output);
  });

  it('construirSobreSoap (SOAP envelope) matches byte-for-byte', () => {
    const xmlInterno = rndc.construirXmlInterno(
      fixtures.construirXmlInterno!.input.tipo as string,
      fixtures.construirXmlInterno!.input.procesoid as number,
      fixtures.construirXmlInterno!.input.variables as Record<string, string | null>,
    );
    expect(rndc.construirSobreSoap(xmlInterno)).toBe(fixtures.construirSobreSoap!.output);
  });

  it('SOAP envelope encoded as ISO-8859-1 matches the PHP wire bytes', () => {
    const xmlInterno = rndc.construirXmlInterno(
      fixtures.construirXmlInterno!.input.tipo as string,
      fixtures.construirXmlInterno!.input.procesoid as number,
      fixtures.construirXmlInterno!.input.variables as Record<string, string | null>,
    );
    const sobre = rndc.construirSobreSoap(xmlInterno);
    const base64 = iconv.encode(sobre, 'ISO-8859-1').toString('base64');
    expect(base64).toBe(fixtures.sobreSoapIso88591Base64!.output);
  });

  it('previewXmlInterno (nested variables) matches byte-for-byte', () => {
    const f = fixtures.previewXmlInterno!;
    const out = rndc.previewXmlInterno(f.input.procesoid as number, f.input.variablesXml as string);
    expect(out).toBe(f.output);
  });

  it('renderVariables matches byte-for-byte', () => {
    const f = fixtures.renderVariables!;
    expect(RndcClient.renderVariables(f.input.vars as Record<string, string | null>)).toBe(f.output);
  });

  it('construirXmlConsulta matches byte-for-byte', () => {
    const f = fixtures.construirXmlConsulta!;
    const out = rndc.construirXmlConsulta(
      f.input.tipo as string,
      f.input.procesoid as number,
      f.input.campos as string[],
      f.input.filtro as Record<string, string>,
      f.input.rango as Record<string, string>,
    );
    expect(out).toBe(f.output);
  });

  it('escaparXml matches byte-for-byte', () => {
    const f = fixtures.escaparXml!;
    expect(RndcClient.escaparXml(f.input.valor as string)).toBe(f.output);
  });
});
