-- migracion_v19_municipios.sql
--
-- DEPRECATED / NO-OP. This used to TRUNCATE municipio and reload it from a
-- flatter 1122-row DIVIPOLA list that only had top-level municipios and never
-- populated nombre_mpio — breaking the "{nombre} – {nombre_mpio}, {departamento}"
-- picker label (see MunicipioRepo.buscar()) and dropping every corregimiento/
-- comuna entry (e.g. "PALMITAS" under Medellín).
--
-- The correct, complete source of truth is database/municipios.sql (7845 rows,
-- imported as a base file — see DEPLOY.md), which already includes proper
-- nombre_mpio values for every row. Do not re-populate municipio here.
SELECT 1;
